/*
 * The Employee API
 * Creting openApi 3.0 for Spring
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sumit.pack.api;

import com.sumit.pack.models.Employee;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void employeeGetTest() {
        List<Employee> response = api.employeeGet();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void employeeIdDeleteTest() {
        Employee id = null;
        List<Employee> response = api.employeeIdDelete(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * returning all emplyoees with names
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void employeeIdGetTest() {
        Integer id = null;
        List<Employee> response = api.employeeIdGet(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * returning all emplyoees with names
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void employeeNameGetTest() {
        String name = null;
        List<Employee> response = api.employeeNameGet(name);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void employeePostTest() {
        List<Employee> employee = null;
        List<Employee> response = api.employeePost(employee);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * put operation
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void employeePutTest() {
        List<Employee> employee = null;
        List<Employee> response = api.employeePut(employee);

        // TODO: test validations
    }
    
}
